# -*- coding: utf-8 -*-
"""Every state and union territory of India, as the /india/... pages need it.

One entry per state. `lang` is the language that state's own version of the
page is written in - the language most of its small businesses actually work
in, not the one a list of official languages puts first. Where that language
is not one of the eleven the site is translated into (Konkani, Meiteilon,
Khasi, Mizo, the Naga languages, Nepali, Kashmiri) the entry stays on English,
because a page in a language nobody reading it uses is worse than an honest
English one.

`cities` are the places a business owner there would name as the working
towns, not the five largest by population. `trade` names the kinds of small
business that are actually common there - it is what makes the page about that
state rather than a find-and-replace of the last one, so keep it true.
"""

STATES = [
    # ---- States -----------------------------------------------------------
    dict(slug="andhra-pradesh", name="Andhra Pradesh", native="ఆంధ్రప్రదేశ్", lang="te", iso="IN-AP",
         cities=["Visakhapatnam", "Vijayawada", "Guntur", "Tirupati", "Nellore"],
         cities_native=["విశాఖపట్నం", "విజయవాడ", "గుంటూరు", "తిరుపతి", "నెల్లూరు"],
         trade="pharmaceutical units, seafood and aquaculture exporters, textile workshops and construction contractors",
         trade_native="ఔషధ యూనిట్లు, రొయ్యలు–మత్స్య ఎగుమతిదారులు, వస్త్ర యూనిట్లు మరియు నిర్మాణ కాంట్రాక్టర్లు"),
    dict(slug="arunachal-pradesh", name="Arunachal Pradesh", native="Arunachal Pradesh", lang="en", iso="IN-AR",
         cities=["Itanagar", "Naharlagun", "Pasighat", "Tezu"],
         cities_native=["Itanagar", "Naharlagun", "Pasighat", "Tezu"],
         trade="government contractors, hotels and travel operators, transport fleets and horticulture businesses",
         trade_native=""),
    dict(slug="assam", name="Assam", native="অসম", lang="as", iso="IN-AS",
         cities=["Guwahati", "Silchar", "Dibrugarh", "Jorhat", "Tezpur"],
         cities_native=["গুৱাহাটী", "শিলচৰ", "ডিব্ৰুগড়", "যোৰহাট", "তেজপুৰ"],
         trade="tea estates and their offices, plywood and food processing units, transport fleets and retail chains",
         trade_native="চাহ বাগিচা আৰু সেইবোৰৰ কাৰ্যালয়, প্লাইউড আৰু খাদ্য প্ৰক্ৰিয়াকৰণ গোট, পৰিবহণ বহৰ আৰু খুচুৰা শৃংখল"),
    dict(slug="bihar", name="Bihar", native="बिहार", lang="hi", iso="IN-BR",
         cities=["Patna", "Muzaffarpur", "Gaya", "Bhagalpur", "Darbhanga"],
         cities_native=["पटना", "मुज़फ़्फ़रपुर", "गया", "भागलपुर", "दरभंगा"],
         trade="distributors and wholesalers, coaching institutes, food processing units and civil contractors",
         trade_native="वितरक और थोक व्यापारी, कोचिंग संस्थान, खाद्य प्रसंस्करण इकाइयाँ और सिविल ठेकेदार"),
    dict(slug="chhattisgarh", name="Chhattisgarh", native="छत्तीसगढ़", lang="hi", iso="IN-CT",
         cities=["Raipur", "Bhilai", "Bilaspur", "Korba", "Durg"],
         cities_native=["रायपुर", "भिलाई", "बिलासपुर", "कोरबा", "दुर्ग"],
         trade="steel and rolling mills, mining service contractors, rice mills and equipment dealers",
         trade_native="इस्पात और रोलिंग मिलें, खनन सेवा ठेकेदार, राइस मिलें और उपकरण डीलर"),
    dict(slug="goa", name="Goa", native="Goa", lang="en", iso="IN-GA",
         cities=["Panaji", "Margao", "Vasco da Gama", "Mapusa", "Verna"],
         cities_native=["Panaji", "Margao", "Vasco da Gama", "Mapusa", "Verna"],
         trade="hotels and resorts, pharmaceutical and electronics units in the industrial estates, tour operators and marine services",
         trade_native=""),
    dict(slug="gujarat", name="Gujarat", native="ગુજરાત", lang="gu", iso="IN-GJ",
         cities=["Ahmedabad", "Surat", "Vadodara", "Rajkot", "Gandhinagar"],
         cities_native=["અમદાવાદ", "સુરત", "વડોદરા", "રાજકોટ", "ગાંધીનગર"],
         trade="diamond and textile units, chemical and engineering workshops, ceramic factories and export houses",
         trade_native="હીરા અને કાપડના એકમો, રસાયણ અને એન્જિનિયરિંગ વર્કશોપ, સિરામિક ફેક્ટરીઓ અને નિકાસ ગૃહો"),
    dict(slug="haryana", name="Haryana", native="हरियाणा", lang="hi", iso="IN-HR",
         cities=["Gurugram", "Faridabad", "Panipat", "Karnal", "Hisar"],
         cities_native=["गुरुग्राम", "फ़रीदाबाद", "पानीपत", "करनाल", "हिसार"],
         trade="auto component suppliers, the textile and handloom units of Panipat, back-office teams in Gurugram and agricultural equipment dealers",
         trade_native="ऑटो कंपोनेंट आपूर्तिकर्ता, पानीपत की कपड़ा और हथकरघा इकाइयाँ, गुरुग्राम की बैक-ऑफ़िस टीमें और कृषि-उपकरण डीलर"),
    dict(slug="himachal-pradesh", name="Himachal Pradesh", native="हिमाचल प्रदेश", lang="hi", iso="IN-HP",
         cities=["Shimla", "Baddi", "Solan", "Dharamshala", "Mandi"],
         cities_native=["शिमला", "बद्दी", "सोलन", "धर्मशाला", "मंडी"],
         trade="the pharmaceutical plants around Baddi, hotels and travel operators, apple packing and cold storage businesses",
         trade_native="बद्दी के आसपास की दवा इकाइयाँ, होटल और ट्रैवल ऑपरेटर, सेब पैकिंग और कोल्ड स्टोरेज कारोबार"),
    dict(slug="jharkhand", name="Jharkhand", native="झारखंड", lang="hi", iso="IN-JH",
         cities=["Ranchi", "Jamshedpur", "Dhanbad", "Bokaro", "Hazaribagh"],
         cities_native=["राँची", "जमशेदपुर", "धनबाद", "बोकारो", "हज़ारीबाग़"],
         trade="engineering workshops feeding the steel plants, mining contractors, transport fleets and equipment hire",
         trade_native="इस्पात संयंत्रों को आपूर्ति करने वाली इंजीनियरिंग वर्कशॉप, खनन ठेकेदार, ट्रांसपोर्ट बेड़े और उपकरण किराया"),
    dict(slug="karnataka", name="Karnataka", native="ಕರ್ನಾಟಕ", lang="kn", iso="IN-KA",
         cities=["Bengaluru", "Mysuru", "Hubballi", "Mangaluru", "Belagavi"],
         cities_native=["ಬೆಂಗಳೂರು", "ಮೈಸೂರು", "ಹುಬ್ಬಳ್ಳಿ", "ಮಂಗಳೂರು", "ಬೆಳಗಾವಿ"],
         trade="software and IT services teams, machine shops and precision engineering, garment units and logistics operators",
         trade_native="ತಂತ್ರಾಂಶ ಮತ್ತು ಐಟಿ ಸೇವಾ ತಂಡಗಳು, ಯಂತ್ರೋಪಕರಣ ಮತ್ತು ನಿಖರ ಎಂಜಿನಿಯರಿಂಗ್, ಉಡುಪು ಘಟಕಗಳು ಮತ್ತು ಸರಕು ಸಾಗಣೆ ಸಂಸ್ಥೆಗಳು"),
    dict(slug="kerala", name="Kerala", native="കേരളം", lang="ml", iso="IN-KL",
         cities=["Kochi", "Thiruvananthapuram", "Kozhikode", "Thrissur", "Kollam"],
         cities_native=["കൊച്ചി", "തിരുവനന്തപുരം", "കോഴിക്കോട്", "തൃശ്ശൂർ", "കൊല്ലം"],
         trade="spice and seafood exporters, hospitals and diagnostic chains, the IT teams in the technoparks, jewellery and construction firms",
         trade_native="സുഗന്ധവ്യഞ്ജന–സമുദ്രോത്പന്ന കയറ്റുമതിക്കാർ, ആശുപത്രികളും ഡയഗ്നോസ്റ്റിക് ശൃംഖലകളും, ടെക്നോപാർക്കിലെ ഐടി സംഘങ്ങൾ, ജ്വല്ലറി, നിർമ്മാണ സ്ഥാപനങ്ങൾ"),
    dict(slug="madhya-pradesh", name="Madhya Pradesh", native="मध्य प्रदेश", lang="hi", iso="IN-MP",
         cities=["Indore", "Bhopal", "Jabalpur", "Gwalior", "Ujjain"],
         cities_native=["इंदौर", "भोपाल", "जबलपुर", "ग्वालियर", "उज्जैन"],
         trade="soya and pulse processing, the pharmaceutical and auto-part units around Pithampur, distributors and coaching institutes",
         trade_native="सोया और दाल प्रसंस्करण, पीथमपुर के आसपास दवा और ऑटो-पार्ट इकाइयाँ, वितरक और कोचिंग संस्थान"),
    dict(slug="maharashtra", name="Maharashtra", native="महाराष्ट्र", lang="mr", iso="IN-MH",
         cities=["Mumbai", "Pune", "Nagpur", "Nashik", "Chhatrapati Sambhajinagar"],
         cities_native=["मुंबई", "पुणे", "नागपूर", "नाशिक", "छत्रपती संभाजीनगर"],
         trade="engineering and auto-component workshops, chartered accountants and financial services, logistics operators, film and media production",
         trade_native="अभियांत्रिकी आणि वाहन-सुटे भाग कार्यशाळा, सनदी लेखापाल आणि वित्तीय सेवा, वाहतूक व्यवस्थापक, चित्रपट व माध्यम निर्मिती"),
    dict(slug="manipur", name="Manipur", native="Manipur", lang="en", iso="IN-MN",
         cities=["Imphal", "Thoubal", "Churachandpur", "Bishnupur"],
         cities_native=["Imphal", "Thoubal", "Churachandpur", "Bishnupur"],
         trade="handloom and handicraft units, food processing, government contractors and retail distributors",
         trade_native=""),
    dict(slug="meghalaya", name="Meghalaya", native="Meghalaya", lang="en", iso="IN-ML",
         cities=["Shillong", "Tura", "Jowai", "Nongpoh"],
         cities_native=["Shillong", "Tura", "Jowai", "Nongpoh"],
         trade="tourism and hospitality, cement and mining services, transport operators and trading houses",
         trade_native=""),
    dict(slug="mizoram", name="Mizoram", native="Mizoram", lang="en", iso="IN-MZ",
         cities=["Aizawl", "Lunglei", "Champhai", "Serchhip"],
         cities_native=["Aizawl", "Lunglei", "Champhai", "Serchhip"],
         trade="bamboo and horticulture processing, retail distribution, transport and government contracting",
         trade_native=""),
    dict(slug="nagaland", name="Nagaland", native="Nagaland", lang="en", iso="IN-NL",
         cities=["Kohima", "Dimapur", "Mokokchung", "Wokha"],
         cities_native=["Kohima", "Dimapur", "Mokokchung", "Wokha"],
         trade="the trading and distribution businesses of Dimapur, construction contractors, hospitality and food processing",
         trade_native=""),
    dict(slug="odisha", name="Odisha", native="ଓଡ଼ିଶା", lang="or", iso="IN-OR",
         cities=["Bhubaneswar", "Cuttack", "Rourkela", "Sambalpur", "Berhampur"],
         cities_native=["ଭୁବନେଶ୍ୱର", "କଟକ", "ରାଉରକେଲା", "ସମ୍ବଲପୁର", "ବ୍ରହ୍ମପୁର"],
         trade="steel and metal fabrication, mining service contractors, the IT teams in Bhubaneswar, handloom and food processing",
         trade_native="ଇସ୍ପାତ ଓ ଧାତୁ ନିର୍ମାଣ, ଖଣି ସେବା ଠିକାଦାର, ଭୁବନେଶ୍ୱରର ଆଇଟି ଦଳ, ହସ୍ତତନ୍ତ ଓ ଖାଦ୍ୟ ପ୍ରକ୍ରିୟାକରଣ"),
    dict(slug="punjab", name="Punjab", native="ਪੰਜਾਬ", lang="pa", iso="IN-PB",
         cities=["Ludhiana", "Amritsar", "Jalandhar", "Mohali", "Patiala"],
         cities_native=["ਲੁਧਿਆਣਾ", "ਅੰਮ੍ਰਿਤਸਰ", "ਜਲੰਧਰ", "ਮੋਹਾਲੀ", "ਪਟਿਆਲਾ"],
         trade="hosiery and garment units, bicycle and auto-part workshops, agricultural machinery makers, sports goods and food processing",
         trade_native="ਹੌਜ਼ਰੀ ਤੇ ਕੱਪੜਾ ਯੂਨਿਟ, ਸਾਈਕਲ ਤੇ ਆਟੋ-ਪਾਰਟ ਵਰਕਸ਼ਾਪਾਂ, ਖੇਤੀ ਮਸ਼ੀਨਰੀ ਬਣਾਉਣ ਵਾਲੇ, ਖੇਡ ਸਮਾਨ ਤੇ ਖੁਰਾਕ ਪ੍ਰੋਸੈਸਿੰਗ"),
    dict(slug="rajasthan", name="Rajasthan", native="राजस्थान", lang="hi", iso="IN-RJ",
         cities=["Jaipur", "Jodhpur", "Udaipur", "Kota", "Bhilwara"],
         cities_native=["जयपुर", "जोधपुर", "उदयपुर", "कोटा", "भीलवाड़ा"],
         trade="gem and jewellery workshops, handicraft and furniture exporters, the textile mills of Bhilwara, hotels and marble processing",
         trade_native="रत्न और आभूषण कार्यशालाएँ, हस्तशिल्प व फ़र्नीचर निर्यातक, भीलवाड़ा की कपड़ा मिलें, होटल और मार्बल प्रसंस्करण"),
    dict(slug="sikkim", name="Sikkim", native="Sikkim", lang="en", iso="IN-SK",
         cities=["Gangtok", "Namchi", "Gyalshing", "Rangpo"],
         cities_native=["Gangtok", "Namchi", "Gyalshing", "Rangpo"],
         trade="the pharmaceutical units around Rangpo, hotels and tour operators, organic farming and food processing",
         trade_native=""),
    dict(slug="tamil-nadu", name="Tamil Nadu", native="தமிழ்நாடு", lang="ta", iso="IN-TN",
         cities=["Chennai", "Coimbatore", "Madurai", "Tiruppur", "Salem"],
         cities_native=["சென்னை", "கோயம்புத்தூர்", "மதுரை", "திருப்பூர்", "சேலம்"],
         trade="the knitwear units of Tiruppur, pumps and castings in Coimbatore, auto-component suppliers, IT services and leather businesses",
         trade_native="திருப்பூர் பின்னலாடை நிறுவனங்கள், கோயம்புத்தூர் பம்ப் மற்றும் காஸ்டிங் பட்டறைகள், வாகன உதிரிபாக நிறுவனங்கள், ஐடி சேவைகள் மற்றும் தோல் தொழில்"),
    dict(slug="telangana", name="Telangana", native="తెలంగాణ", lang="te", iso="IN-TG",
         cities=["Hyderabad", "Warangal", "Nizamabad", "Karimnagar", "Khammam"],
         cities_native=["హైదరాబాద్", "వరంగల్", "నిజామాబాద్", "కరీంనగర్", "ఖమ్మం"],
         trade="pharmaceutical and bulk drug units, IT and back-office teams, granite processing and construction firms",
         trade_native="ఔషధ మరియు బల్క్ డ్రగ్ యూనిట్లు, ఐటీ మరియు బ్యాక్-ఆఫీస్ బృందాలు, గ్రానైట్ ప్రాసెసింగ్ మరియు నిర్మాణ సంస్థలు"),
    dict(slug="tripura", name="Tripura", native="ত্রিপুরা", lang="bn", iso="IN-TR",
         cities=["Agartala", "Udaipur", "Dharmanagar", "Kailashahar"],
         cities_native=["আগরতলা", "উদয়পুর", "ধর্মনগর", "কৈলাসহর"],
         trade="rubber and bamboo processing, tea gardens, retail distribution and government contracting",
         trade_native="রাবার ও বাঁশ প্রক্রিয়াকরণ, চা বাগান, খুচরো বণ্টন এবং সরকারি ঠিকাদারি"),
    dict(slug="uttar-pradesh", name="Uttar Pradesh", native="उत्तर प्रदेश", lang="hi", iso="IN-UP",
         cities=["Noida", "Lucknow", "Kanpur", "Ghaziabad", "Varanasi", "Agra"],
         cities_native=["नोएडा", "लखनऊ", "कानपुर", "ग़ाज़ियाबाद", "वाराणसी", "आगरा"],
         trade="the electronics and back-office teams of Noida, the leather units of Kanpur, brassware in Moradabad, carpet and garment exporters",
         trade_native="नोएडा की इलेक्ट्रॉनिक्स और बैक-ऑफ़िस टीमें, कानपुर की चमड़ा इकाइयाँ, मुरादाबाद का पीतल उद्योग, कालीन और वस्त्र निर्यातक"),
    dict(slug="uttarakhand", name="Uttarakhand", native="उत्तराखंड", lang="hi", iso="IN-UT",
         cities=["Dehradun", "Haridwar", "Rudrapur", "Haldwani", "Kashipur"],
         cities_native=["देहरादून", "हरिद्वार", "रुद्रपुर", "हल्द्वानी", "काशीपुर"],
         trade="the pharmaceutical and auto-component plants in the SIDCUL estates, hotels and travel operators, food processing units",
         trade_native="सिडकुल क्षेत्रों की दवा और ऑटो-कंपोनेंट इकाइयाँ, होटल और ट्रैवल ऑपरेटर, खाद्य प्रसंस्करण इकाइयाँ"),
    dict(slug="west-bengal", name="West Bengal", native="পশ্চিমবঙ্গ", lang="bn", iso="IN-WB",
         cities=["Kolkata", "Howrah", "Siliguri", "Durgapur", "Asansol"],
         cities_native=["কলকাতা", "হাওড়া", "শিলিগুড়ি", "দুর্গাপুর", "আসানসোল"],
         trade="the engineering workshops of Howrah, jute and leather units, tea trading, printing houses and the IT teams in Salt Lake",
         trade_native="হাওড়ার ইঞ্জিনিয়ারিং কারখানা, পাট ও চামড়ার ইউনিট, চা ব্যবসা, ছাপাখানা এবং সল্টলেকের আইটি দল"),

    # ---- Union territories --------------------------------------------------
    dict(slug="andaman-and-nicobar-islands", name="Andaman and Nicobar Islands", native="Andaman and Nicobar Islands", lang="en", iso="IN-AN",
         cities=["Port Blair", "Havelock", "Diglipur", "Mayabunder"],
         cities_native=["Port Blair", "Havelock", "Diglipur", "Mayabunder"],
         trade="tourism and dive operators, fisheries, shipping agents and construction contractors",
         trade_native=""),
    dict(slug="chandigarh", name="Chandigarh", native="चंडीगढ़", lang="hi", iso="IN-CH",
         cities=["Chandigarh", "Industrial Area Phase I", "Manimajra"],
         cities_native=["चंडीगढ़", "इंडस्ट्रियल एरिया फेज़ 1", "मनीमाजरा"],
         trade="IT and back-office teams, professional practices, hospitality and light engineering units",
         trade_native="आईटी और बैक-ऑफ़िस टीमें, पेशेवर फ़र्में, आतिथ्य और हल्की इंजीनियरिंग इकाइयाँ"),
    dict(slug="dadra-and-nagar-haveli-and-daman-and-diu", name="Dadra and Nagar Haveli and Daman and Diu", native="દાદરા અને નગર હવેલી અને દમણ અને દીવ", lang="gu", iso="IN-DH",
         cities=["Silvassa", "Daman", "Diu", "Vapi"],
         cities_native=["સેલવાસ", "દમણ", "દીવ", "વાપી"],
         trade="the plastics, textile and engineering units in the industrial estates, packaging plants and logistics operators",
         trade_native="ઔદ્યોગિક વસાહતોમાં પ્લાસ્ટિક, કાપડ અને એન્જિનિયરિંગ એકમો, પેકેજિંગ પ્લાન્ટ અને લોજિસ્ટિક્સ સંચાલકો"),
    dict(slug="delhi", name="Delhi", native="दिल्ली", lang="hi", iso="IN-DL",
         cities=["New Delhi", "Okhla", "Rohini", "Dwarka", "Nehru Place"],
         cities_native=["नई दिल्ली", "ओखला", "रोहिणी", "द्वारका", "नेहरू प्लेस"],
         trade="wholesale and export traders, the garment units of Okhla, the IT resellers around Nehru Place, printing and event businesses",
         trade_native="थोक और निर्यात व्यापारी, ओखला की गारमेंट इकाइयाँ, नेहरू प्लेस के आईटी विक्रेता, प्रिंटिंग और इवेंट कारोबार"),
    dict(slug="jammu-and-kashmir", name="Jammu and Kashmir", native="जम्मू और कश्मीर", lang="hi", iso="IN-JK",
         cities=["Srinagar", "Jammu", "Anantnag", "Baramulla", "Udhampur"],
         cities_native=["श्रीनगर", "जम्मू", "अनंतनाग", "बारामूला", "उधमपुर"],
         trade="handicraft and carpet workshops, horticulture and cold storage, hotels and houseboat operators, construction contractors",
         trade_native="हस्तशिल्प और कालीन कार्यशालाएँ, बाग़वानी और कोल्ड स्टोरेज, होटल व हाउसबोट संचालक, निर्माण ठेकेदार"),
    dict(slug="ladakh", name="Ladakh", native="लद्दाख", lang="hi", iso="IN-LA",
         cities=["Leh", "Kargil", "Nubra", "Zanskar"],
         cities_native=["लेह", "कारगिल", "नुब्रा", "ज़ंस्कार"],
         trade="tour and trek operators, hotels and guest houses, transport fleets and construction contractors",
         trade_native="टूर और ट्रेक ऑपरेटर, होटल व गेस्ट हाउस, ट्रांसपोर्ट बेड़े और निर्माण ठेकेदार"),
    dict(slug="lakshadweep", name="Lakshadweep", native="ലക്ഷദ്വീപ്", lang="ml", iso="IN-LD",
         cities=["Kavaratti", "Agatti", "Andrott", "Minicoy"],
         cities_native=["കവരത്തി", "അഗത്തി", "ആന്ത്രോത്ത്", "മിനിക്കോയ്"],
         trade="fisheries and coir units, tourism and resort operators, shipping and supply contractors",
         trade_native="മത്സ്യബന്ധനവും കയർ യൂണിറ്റുകളും, ടൂറിസം–റിസോർട്ട് സ്ഥാപനങ്ങൾ, ഷിപ്പിംഗ്, സപ്ലൈ കരാറുകാർ"),
    dict(slug="puducherry", name="Puducherry", native="புதுச்சேரி", lang="ta", iso="IN-PY",
         cities=["Puducherry", "Karaikal", "Yanam", "Mahe"],
         cities_native=["புதுச்சேரி", "காரைக்கால்", "யானம்", "மாஹே"],
         trade="pharmaceutical and engineering units, hotels and guest houses, textile workshops and IT services",
         trade_native="மருந்து மற்றும் பொறியியல் நிறுவனங்கள், விடுதிகள் மற்றும் விருந்தினர் இல்லங்கள், ஜவுளி பட்டறைகள் மற்றும் ஐடி சேவைகள்"),
]

BY_SLUG = {s["slug"]: s for s in STATES}


def states_for(lang):
    """The states whose own version of the page is written in `lang`."""
    return [s for s in STATES if s["lang"] == lang]
