# -*- coding: utf-8 -*-
"""English - the reference every other language file mirrors.

`tools/build_i18n.py` checks that every other file in this folder has exactly
these keys, so adding a key here and nowhere else fails the build rather than
quietly shipping a page with a hole in it.

The four English pages in public/ are hand-written and are NOT generated from
this file. This copy exists because the /india pages are generated in English
too, and because a translator needs one file to translate from. If you change
the wording of a hand-written English page and want the translations to
follow, change it here as well.

Keys are prefixed by where they are used:
    n_   navigation, footer, the language picker - every page
    h_   the home page
    w_   the WorkQueue page
    p_   the pricing page
    c_   the contact page
    i_   the /india hub and the per-state pages
Anything ending _alt is image alt text. {} placeholders are filled by the
builder and must survive translation.
"""

S = {
    # --- Navigation, footer, chrome -----------------------------------------
    "n_skip": "Skip to content",
    "n_home": "Home",
    "n_workqueue": "WorkQueue",
    "n_pricing": "Pricing",
    "n_contact": "Contact",
    "n_india": "Across India",
    "n_menu": "Menu",
    "n_theme": "Switch theme",
    "n_trial": "Start a trial",
    "n_lang": "Language",
    "n_lang_choose": "Choose your language",
    "n_lang_note": "The whole site is written in each of these, not machine-translated.",

    "f_about": "Small Windows tools for small businesses. Built in Mumbai, India — bought once, run on your own network.",
    "f_tools": "Tools",
    "f_buying": "Buying",
    "f_contact": "Contact",
    "f_requirements": "Requirements",
    "f_next": "What is next",
    "f_free_trial": "Free trial",
    "f_setup": "Guided setup",
    "f_message": "Send a message",
    "f_whatsapp": "WhatsApp",
    "f_states": "Every state",
    "f_rights": "Quietworks. All rights reserved.",
    "f_made": "Made in Mumbai",
    "f_wa_msg": "Hello, I saw the Quietworks website and would like to know more.",

    # --- Home ----------------------------------------------------------------
    "h_title": "Quietworks — task tracking software that runs on your own Wi-Fi",
    "h_desc": "Small, sharp Windows tools for small businesses in India. Buy once, run it on a PC you already own, and keep your data in your office. WorkQueue assigns work to your team and times it automatically.",
    "h_eyebrow": "Software for small teams",
    "h_h1": "Team software that runs on your own Wi-Fi.",
    "h_lede": "We build small, sharp Windows tools for businesses that are tired of paying per person, per month, forever. You buy it once. It runs on a PC you already own. Nothing about your business leaves your office.",
    "h_cta1": "See WorkQueue",
    "h_cta2": "Try it free for 30 days",
    "h_trust1": "One payment, not a subscription",
    "h_trust2": "Your data never leaves the office",
    "h_trust3": "Set up in an afternoon",
    "h_shot_open": "Open the full-size screenshot of the WorkQueue board",
    "h_shot_alt": "The WorkQueue board: a task composer at the top, and three live columns showing Waiting, In progress and Completed today.",
    "h_shot_cap": "The WorkQueue board, open in a browser on the manager's PC. Click it for the full screen.",

    "h_film_eyebrow": "See it work",
    "h_film_h2": "Watch one task go out and come back.",
    "h_film_lede": "A minute of WorkQueue running for real: a job typed on the manager's board, delivered to an employee's strip a couple of seconds later, timed without anybody starting a clock, and turned into a number the moment it is done.",
    "h_film_watch": "Watch the demo",
    "h_film_aria": "Play the demonstration, one minute and seven seconds",
    "h_film_cant": "Your browser cannot play this video.",
    "h_film_download": "Download it instead",
    "h_film_ch1": "Assigned",
    "h_film_ch2": "Delivered",
    "h_film_ch3": "Being worked on",
    "h_film_ch4": "Completed",
    "h_film_ch5": "Counted",
    "h_film_cap1": "The manager types the job once, and picks whose screen it goes to.",
    "h_film_cap2": "It lands on Asha's strip about two seconds later. There is no app to open and nothing to accept — reaching her PC is what counts as delivered.",
    "h_film_cap3": "The clock started itself the moment the task arrived, and the board shows it running. Nobody has to remember to start a timer.",
    "h_film_cap4": "She presses Complete once. Her strip goes quiet and the card crosses the board on its own.",
    "h_film_cap5": "Response five seconds, work twenty-four. Two timestamps nobody typed — and thirty days of them is the reporting.",
    "h_film_note": "Recorded against WorkQueue 4.0.1 and a database of demo data. The dashboard is captured from the browser; the strip is captured from the top of a real Windows desktop, at its real size. The names are invented — everything they are doing is not. The words on screen in the film are in English.",

    "h_why_eyebrow": "Why we exist",
    "h_why_h2": "Most business software is rented, not owned.",
    "h_why_lede": "A ten-person team on a typical task tool pays somewhere near ₹90,000 a year, every year, to store their own work on someone else's computer. For a lot of small businesses that maths never made sense.",
    "h_why1_h": "Your data stays yours",
    "h_why1_p": "Everything lives in one file on a PC in your own office. No third-party servers, no data-processing agreement to read, nothing to leak if a vendor gets breached.",
    "h_why2_h": "One price, then it is yours",
    "h_why2_p": "Pay once for the company, not monthly for every person. Hire five more people and the bill does not move. There is no meter running while you sleep.",
    "h_why3_h": "It works when the internet does not",
    "h_why3_p": "Your broadband drops; your team keeps working. Everything runs over the office network, so an outage at your ISP is somebody else's problem.",

    "h_tool_eyebrow": "The first tool",
    "h_tool_h2": "WorkQueue — hand out work, and know how long it took.",
    "h_tool_lede": "A manager assigns tasks from a browser. Every employee sees their own queue in a thin strip at the top of their screen — not an app they have to remember to open. The clock starts by itself, and stops when they press Complete.",

    "h_f1_h": "Nobody has to remember to check anything",
    "h_f1_p": "The strip is docked into Windows the same way the taskbar is. It is always there, it never covers a window, and a new task appears on it within seconds of being assigned.",
    "h_f1_l1_b": "No app to open.",
    "h_f1_l1": "The queue is already on screen, all day.",
    "h_f1_l2_b": "No accept step.",
    "h_f1_l2": "A task is logged as received the moment it reaches their PC.",
    "h_f1_l3_b": "One button.",
    "h_f1_l3": "When the job is done they press Complete. That is the whole workflow.",
    "h_f1_link": "How the whole thing works",
    "h_f1_alt_left": "The left end of the employee strip: a green connected dot, the name Asha Rao, then a red diamond and the task title Reconcile the September invoice batch.",
    "h_f1_alt_chips": "The right end of the employee strip: three colour-coded chips, one per open task, and a small menu arrow.",
    "h_f1_cap": "The two ends of the strip, at actual size: their name and the task they are on, and a chip for every other task waiting. The whole interface is 34 pixels tall.",

    "h_f2_h": "Timing you did not have to ask anyone for",
    "h_f2_p": "Because the two timestamps are captured automatically, you get real numbers without a single person filling in a timesheet: how long work waited before it was seen, how long it took, who is carrying the load, what is running late.",
    "h_f2_l1_b": "Response time",
    "h_f2_l1": "— assigned until it reached their screen.",
    "h_f2_l2_b": "Work time",
    "h_f2_l2": "— reached their screen until Complete.",
    "h_f2_l3_b": "Ten charts and a CSV export",
    "h_f2_l3": "that match whatever you have filtered on screen.",
    "h_f2_link": "See the reporting",
    "h_f2_alt": "The analytics tab: KPI tiles for completed tasks, work time, average per task, response time and on-time rate, above charts of completed per day and work time per day.",
    "h_f2_cap": "Thirty days of a five-person team, with no timesheets involved.",

    "h_start_eyebrow": "Getting started",
    "h_start_h2": "Three double-clicks and you are running.",
    "h_start_lede": "There is no account to create, no card to enter and no cloud region to choose. Everything installs from a folder you can carry on a USB stick.",
    "h_s1_h": "Install the server",
    "h_s1_p": "Run one file on the PC that stays switched on — the manager's machine is usually the right one. It starts itself at boot from then on, and prints the web address for the dashboard.",
    "h_s2_h": "Install the strip",
    "h_s2_p": "Run one file on each employee PC. It finds the server on the network by itself, so there is no address to type and no admin password to chase.",
    "h_s3_h": "Name the machines",
    "h_s3_p": "Open the dashboard, type each person's name next to their PC, and start assigning. That name is what appears on their strip and in every report.",

    "h_faq_eyebrow": "Questions",
    "h_faq_h2": "The things people ask first",
    "h_faq_q1": "Do we need a server, or IT people?",
    "h_faq_a1": "Neither. The \"server\" is a program that runs on an ordinary Windows PC you already have — usually the manager's. If someone in the office can install a printer, they can install this. If you would rather not, we will do it for you over a remote session.",
    "h_faq_q2": "What happens when the Wi-Fi goes down?",
    "h_faq_a2": "Employees keep seeing their tasks and keep marking them complete. Those actions queue up on their own PC with the real time they were clicked, and are delivered when the network comes back — so a task finished at 10:35 during an outage is still recorded as 10:35.",
    "h_faq_q3": "Can people use it from home, or from another branch?",
    "h_faq_a3": "Yes. WorkQueue can be joined to a private network (Tailscale) so laptops outside the office reach the same server securely, with nothing exposed to the public internet. It is one extra step during setup, and it is included.",
    "h_faq_q4": "Is this only for Windows?",
    "h_faq_a4": "Today, yes — both the dashboard PC and the employee PCs need Windows 10 or 11. The dashboard itself is just a web page, so it opens on any device on your network, including a phone. Mac and Linux employee support is on the roadmap rather than in the box, and we would rather say so plainly.",
    "h_faq_q5": "What do we get for the money, exactly?",
    "h_faq_a5": "A licence for your whole company — every PC in the office, no per-seat counting — a year of updates, and email support. Full details are on the pricing page.",

    "h_cta_h2": "Try it on your own team for 30 days.",
    "h_cta_p": "The full tool, no feature held back, nothing to cancel. Tell us roughly how many PCs you have and we will send the installer and walk you through it.",
    "h_cta_b1": "Request the trial",
    "h_cta_b2": "See the price",

    # --- WorkQueue -----------------------------------------------------------
    "w_title": "WorkQueue — an employee task tracker for your own network",
    "w_desc": "WorkQueue hands tasks to your team through a 34-pixel strip at the top of their screen, times every job automatically, and reports on it. Runs on your own Windows PCs. One payment for the whole company.",
    "w_eyebrow": "WorkQueue",
    "w_h1": "Hand out work. Know exactly how long it took.",
    "w_lede": "A manager assigns from a browser. Every employee sees their own queue in a thin strip docked at the top of their screen. Both timestamps are captured for you, so the reporting is a by-product of people simply doing their work.",
    "w_trust1": "Windows 10 and 11",
    "w_trust2": "No cloud account",
    "w_trust3": "Unlimited PCs on one licence",
    "w_hero_alt": "The WorkQueue board with a task composer and three columns: Waiting, In progress and Completed today.",
    "w_hero_cap": "One row to assign. Three columns to watch.",

    "w_strip_eyebrow": "The employee side",
    "w_strip_h2": "34 pixels. That is the entire thing your staff have to learn.",
    "w_strip_lede": "The strip docks into Windows the same way the taskbar does, so Windows reserves the space for it and maximised windows simply stop below. It cannot cover anyone's work, and nothing can cover it.",
    "w_strip_alt": "The whole strip across the top of a 1920-pixel screen: the employee name and current task at the left, a chip for each open task at the right, and a great deal of empty space between them.",
    "w_strip_cap": "The whole strip, across a 1920-pixel screen. This is roughly how much of the display it takes — which is the point. The two close-ups below are the same strip at actual size.",
    "w_strip_left_b": "Left end.",
    "w_strip_left": "A green dot while the server is reachable, their name, and the task they are on. The red diamond means urgent.",
    "w_strip_right_b": "Right end.",
    "w_strip_right": "One chip per open task, coloured by priority. Clicking one switches to it; the frame takes its colour.",
    "w_panel_alt": "The panel opened from the strip: the current task with its description and assigned time on the left above one large Mark completed button, and the employee's three tasks listed on the right, each with its own Complete button.",
    "w_panel_cap": "Clicking a task opens this. One big button to finish the job, a box to ask the admin a question, and every other task one click away.",

    "w_c1_h": "There is no Accept button",
    "w_c1_p": "A task is marked received the instant it reaches their machine. Nobody can forget to acknowledge work, and the gap between \"assigned\" and \"on their screen\" becomes a number you can actually manage.",
    "w_c2_h": "One button to finish",
    "w_c2_p": "Click a task to open the panel: the description, any comments, and one large Complete button that asks for a second click so it cannot happen by accident.",
    "w_c3_h": "They can talk back",
    "w_c3_p": "An employee can leave a comment on a task — a question, a blocker, a note on what they found. You see it and reply from the same task in the dashboard.",

    "w_board_eyebrow": "The board",
    "w_board_h3": "Assign in one line, then watch the day move",
    "w_board_p": "A title, any detail the person needs, a priority, a due date, who it goes to, and Assign. Send the same task to one person or to six.",
    "w_board_l1_b": "Three live columns",
    "w_board_l1": "— waiting, in progress, and completed today, grouped by person.",
    "w_board_l2_b": "Act without interrupting anyone",
    "w_board_l2": "— Done, Cancel, Reopen and Delete appear on a card when you point at it.",
    "w_board_l3_b": "Move work around",
    "w_board_l3": "— open a task and reassign it to somebody else.",
    "w_board_l4_b": "Urgent looks urgent",
    "w_board_l4": "— priority colours the card and the employee's strip frame.",
    "w_board_alt": "The board with five waiting tasks, three in progress and twelve completed today.",

    "w_an_eyebrow": "Analytics",
    "w_an_h3": "The questions a manager actually asks",
    "w_an_p": "Seven headline numbers and ten charts, all driven by one filter row. Every chart has a table twin, so you can read the figures rather than squint at bars.",
    "w_an_l1_b": "How much got done",
    "w_an_l1": "— completed against assigned, per day.",
    "w_an_l2_b": "How long things take",
    "w_an_l2": "— average and median per task, and the longest jobs of the period.",
    "w_an_l3_b": "How fast work is picked up",
    "w_an_l3": "— response time per day and per person.",
    "w_an_l4_b": "Who is carrying what",
    "w_an_l4": "— count, hours, response and on-time rate per employee.",
    "w_an_l5_b": "When your team is busy",
    "w_an_l5": "— by hour of day and by day of week.",
    "w_an_alt": "Analytics: 164 completed, 7d 7h of work time, 1h 4m average per task, 21m average response, 95% on time, plus charts.",
    "w_an_cap": "Light by default, dark if you prefer — the whole dashboard has both.",

    "w_hist_eyebrow": "History and calendar",
    "w_hist_h3": "Every task keeps its own paper trail",
    "w_hist_p": "Filter history by person and date range and you get response time and work time on every row, per-person totals at the bottom, and a CSV export that matches exactly what is on screen — the one your accountant or your client actually wants.",
    "w_hist_l1_b": "Click any task title, anywhere,",
    "w_hist_l1": "to open its full timeline.",
    "w_hist_l2_b": "The calendar",
    "w_hist_l2": "heat-shades the month so a slow week is visible at a glance.",
    "w_hist_l3_b": "Reopen a finished task",
    "w_hist_l3": "straight from its row if it comes back.",
    "w_hist_alt": "The calendar tab: a heat-shaded month beside the list of completed tasks, newest day first.",

    "w_res_eyebrow": "When things go wrong",
    "w_res_h2": "Built for an office, not for a demo.",
    "w_res_lede": "Small offices have bad afternoons. The router reboots, the broadband dies, somebody switches off the wrong PC. Each of these was designed for rather than discovered.",
    "w_res_l1_b": "The network drops.",
    "w_res_l1": "Completions and comments go into a local outbox and are delivered when the server returns — each carrying the original click time, so a task finished at 10:35 during a three-hour outage is still recorded at 10:35, not at 13:35.",
    "w_res_l2_b": "Something gets sent twice.",
    "w_res_l2": "Every action carries a unique id the server recognises, so a retry after a dropped connection can never double-count a task.",
    "w_res_l3_b": "The server PC changes IP.",
    "w_res_l3": "The strip broadcasts on the local network and the server answers with its new address. If your router blocks broadcasts — common on mesh and ISP routers — it scans the network instead.",
    "w_res_l4_b": "Nothing works and nobody knows why.",
    "w_res_l4": "A built-in check walks through the eight usual causes — firewall, Wi-Fi isolation, VPN, wrong address — and tells you in plain words which one it is.",

    "w_arch_eyebrow": "How it fits together",
    "w_arch_h2": "Two programs, one network, no cloud.",
    "w_arch_lede": "The whole system is a program on the manager's PC and a small program on each employee's. They talk to each other over the office network and nowhere else.",
    "w_arch_dtitle": "WorkQueue architecture",
    "w_arch_ddesc": "The manager's PC runs the WorkQueue server with a SQLite database and a browser dashboard. Each employee PC runs the WorkQueue bar, which talks to the server over HTTP on port 8420 and finds it using UDP broadcast on port 8421. Everything stays inside the office network.",
    "w_arch_manager": "Manager's PC",
    "w_arch_m1": "workqueue-server.exe",
    "w_arch_m2": "one SQLite database file",
    "w_arch_m3": "dashboard opens in a browser",
    "w_arch_employee": "Employee PC",
    "w_arch_e1": "workqueue-bar.exe · 34px strip",
    "w_arch_http": "HTTP :8420",
    "w_arch_udp": "UDP :8421 finds the server",
    "w_arch_inside": "everything above stays inside your office network",
    "w_arch_c1_h": "Away from the office?",
    "w_arch_c1_p": "WorkQueue can join a private network (Tailscale) so a laptop at home or a second branch reaches the same server, encrypted, with nothing published to the public internet. Setup is one extra step and it is included in the licence.",
    "w_arch_c2_h": "Backups are one file",
    "w_arch_c2_p": "Everything the system knows is a single database. The dashboard exports it while the server keeps running — either a full snapshot with a checksum, or a byte-exact copy of the database. Keep it off that PC and you are covered.",

    "w_cel_eyebrow": "One nice thing",
    "w_cel_h2": "It can also throw a small party.",
    "w_cel_lede": "Send a card instead of a task — a birthday, a work anniversary, a win, a welcome. Balloons drift across that person's strip, and there is a one-minute game in the panel if they want it. A card never enters the history, the analytics or anyone's work time. It is not a task, and it takes itself down after a day.",
    "w_cel_note": "We mention it because monitoring software has a reputation, and a tool your team resents is a tool that quietly stops being used.",

    "w_req_eyebrow": "The specifics",
    "w_req_h2": "What you need to run it",
    "w_req_d1t": "Manager's PC",
    "w_req_d1d": "Windows 10 or 11, left switched on during working hours. No dedicated server, no special hardware. Administrator rights are needed once, for the install.",
    "w_req_d2t": "Employee PCs",
    "w_req_d2d": "Windows 10 or 11. No administrator rights needed — the strip installs for the logged-in user.",
    "w_req_d3t": "Network",
    "w_req_d3d": "All the PCs on the same office network, wired or Wi-Fi. TCP port 8420 and UDP port 8421 open between them — the installer opens the firewall for you.",
    "w_req_d4t": "Internet",
    "w_req_d4d": "Not required. Only needed if you turn on remote access for people outside the office.",
    "w_req_d5t": "Dashboard",
    "w_req_d5d": "Any modern browser on any device on the network, including a phone or tablet.",
    "w_req_d6t": "Install time",
    "w_req_d6d": "About ten minutes for the server and under a minute per employee PC.",

    "w_not_h3": "And what it does not do",
    "w_not_p": "We would rather you read this now than find out in month two.",
    "w_not_l1_b": "It is Windows only.",
    "w_not_l1": "Mac and Linux employee machines are not supported yet.",
    "w_not_l2_b": "People are identified by their PC,",
    "w_not_l2": "not by a login. That is the right trade for a trusted office network, but it does mean a determined person could pretend to be another machine.",
    "w_not_l3_b": "Work time is wall-clock time.",
    "w_not_l3": "If a task stays open over lunch, lunch is in the number. It measures elapsed time, not effort.",
    "w_not_l4_b": "Off the network, the queue goes stale.",
    "w_not_l4": "A laptop away from the office shows its last known tasks until it reconnects — unless you turn on remote access.",
    "w_not_l5_b": "The strip costs 34 pixels",
    "w_not_l5": "of height on the primary monitor, permanently.",

    "w_faq_eyebrow": "Questions",
    "w_faq_h2": "About WorkQueue specifically",
    "w_faq_q1": "Is this employee monitoring? Will my team hate it?",
    "w_faq_a1": "It records two things per task: when it reached the screen and when the person pressed Complete. It does not take screenshots, log keystrokes, track idle time or watch which websites anyone visits, and it never will — that is a deliberate line, not an oversight. In practice teams tend to like it, because \"I sent you that hours ago\" arguments stop being arguments. Everyone is looking at the same timestamps.",
    "w_faq_q2": "How many people can it handle?",
    "w_faq_a2": "It is built and load-tested for a single office — around 25 machines at once on ordinary hardware, with responses well under a tenth of a second. If you are bigger than that, talk to us before you buy rather than after.",
    "w_faq_q3": "What if the manager's PC dies?",
    "w_faq_a3": "Install the server on another PC and import your last export. This is why the backup is one file and why the dashboard nags you to keep a copy somewhere else. Employee PCs find the new server by themselves.",
    "w_faq_q4": "Can I get my data out?",
    "w_faq_a4": "Yes, at any time and without asking us. History exports to CSV, and the whole database exports as a JSON snapshot or as the SQLite file itself. There is no lock-in because there is nothing of yours on our side to lock.",
    "w_faq_q5": "Do you see any of our tasks?",
    "w_faq_a5": "No. The software never contacts us. There is no telemetry, no licence check-in and no analytics call. If your office had no internet at all, WorkQueue would not notice.",
    "w_faq_q6": "What does support look like?",
    "w_faq_a6": "Email, answered within one working day, by the person who wrote the software. The licence includes a year of it, along with a year of updates.",

    "w_cta_h2": "Put it on your own team for 30 days.",
    "w_cta_p": "The complete tool, nothing held back, nothing to cancel. Tell us roughly how many PCs you have and we will send the installer and stay on the call while you set it up.",

    # --- Pricing -------------------------------------------------------------
    "p_title": "WorkQueue pricing — one payment, no per-user fee",
    "p_desc": "WorkQueue costs ₹14,999 once for your entire company — unlimited PCs, a year of updates and support, and no monthly fee. Free 30-day trial. GST invoice for Indian businesses.",
    "p_eyebrow": "Pricing",
    "p_h1": "One payment. Your whole company.",
    "p_lede": "Not per person, not per month, not per project. You buy WorkQueue once, install it on as many PCs as your office has, and it keeps working for as long as those PCs do.",

    "p_trial_h": "Trial",
    "p_trial_tag": "The complete tool, on your own team.",
    "p_trial_amt": "Free",
    "p_trial_per": "for 30 days",
    "p_trial_alt": "No card, nothing to cancel.",
    "p_trial_btn": "Request the trial",
    "p_trial_l1": "Every feature, no limits",
    "p_trial_l2": "Unlimited PCs during the trial",
    "p_trial_l3": "Help getting it installed",
    "p_trial_l4": "Your data carries over if you buy",

    "p_lic_badge": "Most businesses",
    "p_lic_h": "WorkQueue licence",
    "p_lic_tag": "One company, however many PCs.",
    "p_lic_per": "once",
    "p_lic_alt": "$199 outside India · GST extra where applicable",
    "p_lic_btn": "Buy a licence",
    "p_lic_l1_b": "Unlimited PCs",
    "p_lic_l1": "in your business — no seat counting",
    "p_lic_l2_b": "Yours permanently",
    "p_lic_l2": "— it does not stop working, ever",
    "p_lic_l3_b": "One year of updates",
    "p_lic_l3": "and email support",
    "p_lic_l4": "Remote access setup for staff outside the office",
    "p_lic_l5": "Full data export whenever you want it",

    "p_set_h": "Guided setup",
    "p_set_tag": "Optional. We do the installing.",
    "p_set_per": "one-off",
    "p_set_alt": "$99 outside India",
    "p_set_btn": "Add setup",
    "p_set_l1": "Remote install on the server PC and every employee PC",
    "p_set_l2": "Firewall, network and remote access configured",
    "p_set_l3": "One hour of training for whoever assigns the work",
    "p_set_l4": "Two weeks of hand-holding afterwards",

    "p_after_b": "After the first year.",
    "p_after": "Your licence does not expire and the software does not stop — that is the whole point of buying rather than renting. If you want to keep getting new versions and support after twelve months, that is ₹4,999 a year and it is entirely optional. Skip it and keep running the version you have for as long as you like.",

    "p_cmp_eyebrow": "The arithmetic",
    "p_cmp_h2": "What renting the same thing costs.",
    "p_cmp_lede": "Per-seat task tools generally land around ₹600 per person per month. Here is how that compares over three years, which is roughly how long a small business keeps a tool it likes.",
    "p_cmp_caption": "Three-year cost of WorkQueue against a per-seat subscription",
    "p_cmp_th1": "Your team",
    "p_cmp_th2": "WorkQueue, three years",
    "p_cmp_th3": "A per-seat tool, three years",
    "p_cmp_th4": "Difference",
    "p_cmp_r1": "5 people",
    "p_cmp_r2": "10 people",
    "p_cmp_r3": "25 people",
    "p_cmp_once": "once",
    "p_cmp_kept": "kept",
    "p_cmp_note": "Illustrative, using ₹600 per person per month as a typical mid-range figure. Check it against whatever you are actually paying — the comparison only gets better as you hire.",

    "p_inc_eyebrow": "In the box",
    "p_inc_h2": "What the licence actually covers",
    "p_inc_d1t": "Who it covers",
    "p_inc_d1d": "One business, at its own premises. Every PC you own, including new ones you buy later. Separate branches of the same business are included; a different legal entity needs its own licence.",
    "p_inc_d2t": "How long",
    "p_inc_d2d": "Permanently. There is no expiry date and no licence server to check in with — the software would keep running if we vanished tomorrow.",
    "p_inc_d3t": "Updates",
    "p_inc_d3d": "Twelve months of new versions included. After that, renew for ₹4,999 a year or stay on the version you have.",
    "p_inc_d4t": "Support",
    "p_inc_d4d": "Email, answered within one working day, for twelve months. Answered by the person who wrote the software, not a ticket queue.",
    "p_inc_d5t": "Payment",
    "p_inc_d5d": "UPI, bank transfer or card. Invoice with GST provided for Indian businesses.",
    "p_inc_d6t": "If it does not suit you",
    "p_inc_d6d": "The 30-day trial is there so you find that out before paying. If something breaks in the first month after you buy and we cannot fix it, you get your money back.",

    "p_faq_eyebrow": "Questions",
    "p_faq_h2": "About buying",
    "p_faq_q1": "Why is it this cheap?",
    "p_faq_a1": "Because we are not paying for your servers, your storage or your backups — you already own the PC it runs on. Nearly all of what a cloud task tool charges you every month is infrastructure and the sales team needed to keep filling it. WorkQueue has neither.",
    "p_faq_q2": "What if we grow from 8 people to 40?",
    "p_faq_a2": "The price does not change — install it on the new machines and carry on. Do check the requirements though: WorkQueue is built and tested for a single office of roughly 25 machines at once. Past that, talk to us first.",
    "p_faq_q3": "Can we pay monthly instead?",
    "p_faq_a3": "No, and that is deliberate. A monthly plan would mean building the billing, the licence checks and the enforcement that the price is low precisely because we skipped. If the one-off amount is difficult, ask — we would rather split it in two than lose you.",
    "p_faq_q4": "Do you do custom work?",
    "p_faq_a4": "Yes. If WorkQueue is nearly right but your business needs one specific thing it does not do, describe it — sometimes it becomes a feature for everybody, sometimes it is a paid piece of work. Either way you will get a straight answer and a fixed quote.",
    "p_faq_q5": "What happens to our data if we stop paying?",
    "p_faq_a5": "Nothing, because there is nothing to stop paying and your data was never anywhere but your own PC. This is the practical difference between owning software and renting it.",

    "p_cta_h2": "Try it first. Decide after.",
    "p_cta_p": "Thirty days with your real team and your real work is a much better test than any pricing page.",
    "p_cta_b2": "Read how it works",

    # --- Contact -------------------------------------------------------------
    "c_title": "Contact — talk to the person who built it",
    "c_desc": "Ask about a WorkQueue trial, a licence, guided setup, or automating something else in your business. A real reply from a real person within one working day.",
    "c_eyebrow": "Contact",
    "c_h1": "Tell us what you are trying to fix.",
    "c_lede": "A trial, a licence, or a job in your office that currently runs on a shared spreadsheet — all of it starts the same way. You will get a real reply from a real person within one working day.",
    "c_email_l": "Email",
    "c_email_p": "Best for anything with detail in it.",
    "c_wa_l": "WhatsApp",
    "c_wa_link": "Message us",
    "c_wa_p": "Quickest for a short question.",
    "c_hours_l": "Hours",
    "c_hours_v": "Monday to Saturday, 10am to 7pm IST",
    "c_hours_p": "Messages outside that get answered the next working day.",
    "c_form_h": "Send a message",
    "c_form_p": "Only the first three fields are required. The rest just means we can give you a straighter answer first time.",
    "c_f_name": "Your name",
    "c_f_email": "Email",
    "c_f_phone": "Phone",
    "c_f_company": "Business name",
    "c_f_size": "How many PCs?",
    "c_f_enquiry": "What is this about?",
    "c_f_message": "Anything else",
    "c_f_optional": "optional",
    "c_f_send": "Send",
    "c_f_placeholder": "What does the work look like today? Who hands it out, and how do they know it got done?",
    "c_f_privacy": "We use what you send to answer you and nothing else. No list, no newsletter, no passing it on.",
    "c_o_size0": "Not sure yet",
    "c_o_size1": "1 to 5",
    "c_o_size2": "6 to 10",
    "c_o_size3": "11 to 25",
    "c_o_size4": "More than 25",
    "c_o_trial": "Starting a free 30-day trial",
    "c_o_licence": "Buying a WorkQueue licence",
    "c_o_setup": "Guided setup and training",
    "c_o_custom": "Automating something else in my business",
    "c_o_roadmap": "Hearing about new tools",
    "c_o_other": "Something else",
    "c_next_eyebrow": "What happens next",
    "c_next_h2": "No demo carousel, no sales sequence.",
    "c_n1_h": "We reply",
    "c_n1_p": "Within one working day, with an actual answer to what you asked rather than a request for a meeting.",
    "c_n2_h": "You try it",
    "c_n2_p": "We send the installer and, if you want, get on a call while you set it up. Thirty days, everything switched on.",
    "c_n3_h": "You decide",
    "c_n3_p": "Buy it, or do not. If you stop replying we will send one polite note and then leave you alone.",

    # --- India hub and the per-state pages ------------------------------------
    "i_title": "WorkQueue across India — every state and union territory",
    "i_desc": "WorkQueue runs on your own office network anywhere in India, in English and eleven Indian languages. Find the page for your state: what it costs, what it needs, and how to start a free 30-day trial.",
    "i_eyebrow": "Across India",
    "i_h1": "Built in Mumbai. Meant for every office in the country.",
    "i_lede": "WorkQueue does not care which city you are in, because it never leaves your office — it runs on the PCs you already own, over your own Wi-Fi. What does change from place to place is the language your team works in, so the site is written in English and eleven Indian languages, and there is a page for every state and union territory.",
    "i_states_h2": "Pick your state",
    "i_states_p": "Each page is about that state — its working towns, the kinds of business that are common there, and the language most of its offices run on.",
    "i_group_states": "States",
    "i_group_uts": "Union territories",
    "i_langs_h2": "Read it in your own language",
    "i_langs_p": "Every page of this site exists in each of these. Pick one and it is remembered for the next visit.",
    "i_why_h2": "Why this suits an Indian small business in particular",
    "i_why1_h": "It survives your broadband",
    "i_why1_p": "Outages, throttling, a fibre cut down the road — none of it stops work, because nothing needed the internet in the first place. Everything runs over the office LAN or Wi-Fi.",
    "i_why2_h": "One price in rupees, with a GST invoice",
    "i_why2_p": "₹14,999 once for the whole company, paid by UPI, bank transfer or card, with a proper GST invoice for your books. No dollar subscription that moves with the exchange rate.",
    "i_why3_h": "Your team is not asked to learn an app",
    "i_why3_p": "Staff who will never open a project-management tool will still read a strip that is already on their screen. That is the whole reason it is 34 pixels at the top rather than another icon on the desktop.",
    "i_why4_h": "It reads in the language of the floor",
    "i_why4_p": "The site explains itself in eleven Indian languages so the person deciding, the person paying and the person actually using it can each read it in the language they think in.",

    # Per-state page. {state} {hub} {cities} {trade} {lang} are filled in.
    "s_title": "WorkQueue in {state} — task management on your own office network",
    "s_desc": "Assign work and time it automatically for teams in {state} — {cities}. Runs on your own Windows PCs, no cloud, no monthly fee. ₹14,999 once for the whole company. Free 30-day trial.",
    "s_eyebrow": "{state}",
    "s_h1": "Task management for teams in {state} — on your own network.",
    "s_lede": "Whether you are in {hub} or a smaller town, WorkQueue runs on the Windows PCs already in your office. Work goes out from a browser, lands on a strip at the top of each person's screen, and times itself. Nothing about it needs the internet, and nothing about it leaves the building.",
    "s_where_h2": "For businesses in {state}",
    "s_where_p": "We hear from {trade} — the kind of place where work is handed out by phone call, WhatsApp and shouting across the floor, and nobody can say afterwards how long anything took. That is exactly the gap WorkQueue closes.",
    "s_cities_h": "Working in",
    "s_cities_p": "WorkQueue is used the same way everywhere in {state} — it runs on your own network, so there is no regional setup, no data centre to pick and no difference between a head office and a branch.",
    "s_lang_h2": "In {lang}, if that is easier",
    "s_lang_p": "This page and the whole of the rest of the site are written in {lang} as well as English. Nothing is held back in either version.",
    "s_lang_btn": "Read this page in {lang}",
    "s_en_btn": "Read this page in English",
    "s_local_h2": "The practical bits, for {state}",
    "s_local_l1_b": "The power and the broadband.",
    "s_local_l1": "The server PC needs to be switched on during working hours; a small UPS is enough. The internet can be down all day and nobody in the office would notice.",
    "s_local_l2_b": "Buying it.",
    "s_local_l2": "₹14,999 once, by UPI, bank transfer or card, with a GST invoice made out to your business. There is no renewal you have to pay.",
    "s_local_l3_b": "Getting it running.",
    "s_local_l3": "Installed remotely over a call, from anywhere in {state} — about ten minutes for the server and under a minute per employee PC. Guided setup is available if you would rather not touch it.",
    "s_local_l4_b": "Support.",
    "s_local_l4": "Email, answered within one working day, IST, by the person who wrote the software. Ask in {lang} or in English.",
    "s_local_l4_en": "Email, answered within one working day, IST, by the person who wrote the software.",
    "s_other_h2": "Somewhere else in India?",
    "s_other_p": "There is a page for every state and union territory.",
    "s_other_btn": "See all of them",
    "s_cta_h2": "Try it in your own office in {state}, free for 30 days.",
    "s_cta_p": "The complete tool, nothing held back and nothing to cancel. Tell us roughly how many PCs you have and we will send the installer and stay on the call while you set it up.",
    "s_bc_home": "Home",
    "s_bc_india": "Across India",
}
